### PR TITLE
Add timestamp to HTTPRequest

### PR DESCRIPTION
**Pull request by sahilm**
Signed-off-by: Vlad Stoian <vstoian@pivotal.io>

### CODE REVIEW

**Comment by smotes** [comment]
Thanks for this, @sahilm.

It looks like the client's integration tests need to be updated to account for the timestamp as well. I think the `TestClient_DeleteRequests` function is the only one that actually inspects the saved request values.

**Comment by sahilm** [comment]
Thanks for the review. As the test code stands today there isn't a straightforward way to fix this because the tests do an exact deep equality check.

How would you like me to tackle this? I can think of a few options:
1. Pull out the timestamp from the request, assert that it's not empty and then delete the timestamp key before calling `testutil.ExpectEqual`.
1. Put in special handling for the timestamp field in `testutil.ExpectEqual`.
1. Write a `testutil.ExpectRequestsEqual` with timestamp handling in there.
1. Use a more powerful test matching library such as [gomega](https://onsi.github.io/gomega/#matchregexpregexp-string-args-interface).

Let me know which approach suits you all best. I wouldn't want to implement something before running it by you folks. Also, feel free to suggest any other approach.

**Comment by sahilm** [comment]
@smotes Have you had a chance to look at this yet?

**Comment by smotes** [comment]
Hi @sahilm. For the sake of simplicity and avoiding dependencies, I think the first approach might be the best for now. If we run into more troublesome cases in the future it might be worth trying 2 or 3.

**Comment by sahilm** [comment]
Hey @smotes. Sorry for getting back so late. I've fixed all the things :)

**Comment by smotes** [comment]
Thanks for this, @sahilm. Your changes have been merged into `master`.

**Pull request merged**
